safe: true
lsi: false
pygments: true
exclude: ['page_template.html', 'index_template.html', 'README.md', 'TODO.md', 'Gemfile', 'Gemfile.lock']
include: ['.htaccess']
timezone: America/Chicago
name: "Wrist Presenter, Wireless Presentation Control with the Pebble Smartwatch"
description: "Wrist Presenter is an iOS app that lets you control presentation wirelessly with your Pebble Smartwatch."
keywords:
- Matthew Morey
- iOS App
- Pebble Smartwatch
url: http://wristpresenter.com
ios_app_id: 735128848 
ios_app_url: "https://itunes.apple.com/us/app/wrist-presenter-wireless-presentation/id735128848?mt=8&amp;at=10l6oV&amp;ct=wp_website"
android_app_url: "https://play.google.com/store/apps/details?id=com.dandydev.wristpresenter"